### ISSUE TITLE
Catch "Cannot supply flags when constructing one RegExp from another"

### ISSUE THREAD

**Issue by ThaKing** [tornaia/karma-sonarqube-unit-reporter#1]
During running tests with your reporter, I had catch an error "Cannot supply flags when constructing one RegExp from another" on code :
var nextPath = getClassName(browser, result).replace(new RegExp(/\\/, 'g'), '/'); (line 116)

have changed to :
var nextPath = getClassName(browser, result).replace(/\\/g, '/');

everything passed

**Comment by tornaia** [comment]
Many thanks for the report!

Fixed in 0.0.2. Please confirm or will close the issue soon.
