### ISSUE TITLE
Junit Xml file output missing the correct filepath to the testcase - Sonarqube import fails !

### ISSUE THREAD

**Issue by OttawaIan** [tornaia/karma-sonarqube-unit-reporter#14]
Is there some setting where the filepath displays the path to the file ?

 <file path="viewmodel spec">
    <testCase name="VM spec Should fetch" duration="15"/>
    <testCase name="VM spec should get an errror" duration="3"/>
  </file>

For it to get properly pulled into sonarqube using the genericplugin I need the file path to the testcase, otherwise the testcase gets ignored and not counted.  When I manually changed it to the correct path things worked.  

 <file path="test/main/components/viewmodelSpec.js">
    <testCase name="VM spec Should fetch" duration="15"/>
    <testCase name="VM spec should get an errror" duration="3"/>
  </file>

my karma file looks like so:

  reporters: ['progress','junit','sonarqubeUnit', 'coverage'],
    sonarQubeUnitReporter: {
      outputFile: 'reports/junit/ut_report.xml',
      useBrowserName: false
    },
    junitReporter: {
      outputFile: 'TEST-frontend-results.xml',
      outputDir: 'reports/junit',
    },

**Comment by nsleigh** [comment]
I am seeing this problem too, if I edit the report file to look like this it imports ok:
<file path="tests/unit/utils/ribbon/RibbonButton.spec.js">

Note you seem to need the full path as sonar doesn't use the sonar.tests value (in this case it is set to tests/unit).

**Comment by lodybo** [comment]
This is fixed in #17, I used it in a test run and it appears to be working. Any ETA on when this could be merged?

**Comment by tornaia** [comment]
Will be merged around next Tuesday/Wednesday.

**Comment by tornaia** [comment]
Fixed in PR#17 and new version was just released: 0.0.12.
