### ISSUE TITLE
The change to 'testExecutions' from 'unitTest' is not backwards compatible 

### ISSUE THREAD

**Issue by PloughingAByteField** [tornaia/karma-sonarqube-unit-reporter#16]
This broke on sonar 5.6, could it be a config option to enable 6.2+ support until a 6.x LTS drops ?

For now hardcoding package.json to 0.0.9

**Comment by tornaia** [comment]
Optional config parameter added. The report's format is dependent on this value:
sonarQubeVersion:
'5.x' -> <unitTest version="1">
'LATEST'/default -> <testExecutions version="1">

See readme for the updated example.

I know that it is not exactly the solution you proposed but I hope it solves your issue. So you can get rid of the hardcoded 0.0.9 but (until you update your SQ to 6.2+) you have to add an extra sonarQubeVersion config.

0.0.11 is just released.
