### ISSUE TITLE
Cannot find module '../lang/isNative'

### ISSUE THREAD

**Issue by rochejul** [tornaia/karma-sonarqube-unit-reporter#19]
Hi

Here what I get when I use the last version of the plugin:

![image](https://user-images.githubusercontent.com/244999/28457457-7d4fcd9e-6e06-11e7-94dd-a818aa1d8d8a.png)

Regards

**Comment by tornaia** [comment]
Hi,

1. Were you able to use this plugin before the latest  release? Could you please try 0.0.11?
2. Could you please delete the node_modules directory and reinstall?
3. What kind of dependencies do you have in package.json? Maybe there is a conflict somewhere..
4. What is your Node version?

**Comment by rochejul** [comment]
Hi

1) Simply doing "npm install --save-dev karma-sonarqube-unit-reporter"

And as you can see, the last version is "0.0.12" for npm:
![image](https://user-images.githubusercontent.com/244999/28661454-fb69ae5c-72b6-11e7-90ec-a53dd8b6cbe3.png)

And I have tried with 0.0.11: I have no errors but it does not work: Sonarqube does not recognize the file

2) Already done: does not work

3) I have classical karma dependencies for an Angular project:
"karma": "1.7.0",
"karma-chrome-launcher": "2.1.1",
"karma-coverage": "1.1.1",
"karma-jasmine": "1.0.2",
"karma-junit-reporter": "1.2.0",
"karma-ng-html2js-preprocessor": "0.1.2",
"karma-phantomjs-launcher": "1.0.4",
"karma-sonarqube-unit-reporter": "0.0.11"

4) I used node 4.5.0 with npm 2.15.9 on Windows 10

Regards

**Comment by tornaia** [comment]
I'm on vacation atm but will continue with this issue in one and a half week. Thanks for your understanding!

**Comment by rochejul** [comment]
Don't be worry, this is not an emergency issue (for me)

Have a nice holidays

**Comment by Boltyk** [comment]
@rochejul do you still have it on 0.0.14?

**Comment by rochejul** [comment]
Hi
I don't know: I try another way / plugin for that (I do not remember: it was 6 months ago)
Many thanks

Regards
