### ISSUE TITLE
File path is not getting updated in the test results file

### ISSUE THREAD

**Issue by snigdhasambitak** [tornaia/karma-sonarqube-unit-reporter#5]
By using the plugin we are getting the reports in the following format:

<unitTest version="1">
  <file path="myapp">
    <testCase name="works with third party dependencies" duration="9"/>
    <testCase name="loads the controller and html template correctly" duration="6"/>
  </file>
  <file path="myapp enterprise details">
    <testCase name="works with third party dependencies" duration="1"/>
    <testCase name="loads the controller and html template correctly" duration="14"/>
  </file>
</unitTest>

I know currently we can't get the file path using this plugin. Apart from adding the describe('test/unit/some/someTest.js', function() {}" thing is there any other way by which we can get the file path of the tests in the test reports. Is there any reference project for the same?

**Comment by tornaia** [comment]
Im extremely overloaded these days so I will able to show you a reference project only in a few days. 

Thank you for the understanding.

**Comment by tornaia** [comment]
Duplication of https://github.com/tornaia/karma-sonarqube-unit-reporter/issues/2 .
