### ISSUE TITLE
Cannot read property 'children' of undefined at SonarQubeUnitReporter.specSuccess.specSkipped.specFailure at karma-sonar-qube-repoter

### ISSUE THREAD

**Issue by karthik2294** [tornaia/karma-sonarqube-unit-reporter#53]
Angular (Angular 9) Testing is running successfully in local, but it is failing in jenkins server, it happens randomly sometime when i rebuild it get passed, but most of the time, it is failing, this is my packages
{
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-sonarqube-unit-reporter": "0.0.18",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-spec-reporter": "0.0.32",
}

**Karma.Config**

![image](https://user-images.githubusercontent.com/30498296/85835198-3cc7a500-b7b2-11ea-8ac4-d46256fa7927.png)

**Error**
![image](https://user-images.githubusercontent.com/30498296/85835017-f96d3680-b7b1-11ea-9c2e-1d03c49a14b6.png)

please let me know if i need to update something, this is irritating for the past 2 days

**Comment by miguelduarte** [comment]
Hi @karthik2294 ,

How did you solve this problem? I'm running into the same issue and getting the same error

**Comment by seppi91** [comment]
Facing the same issue in our CI Server would be interested in your solution @karthik2294

**Comment by lanfeng** [comment]
@seppi91 @miguelduarte @seppi91  we met the same issue recently. can you please share your solution to fix the issue? thanks

**Comment by rajeshkumar9605** [comment]
Hi @karthik2294 ,

i also getting the same error. could you please help me to solve this?

**Comment by jizzaki** [comment]
We are also getting the same error, would love to know what you did to solve.

**Comment by sebastianteres** [comment]
I opened another issue (#72) since it's not clear how to resolve this.

**Comment by jignesh3094** [comment]
Hello what is the solution of this error?

**Comment by tornaia** [comment]
Fixed in 1.0.0 (#75). The reporter no longer reads the XML back while collecting results, so this crash cannot happen any more; see [CHANGELOG.md](https://github.com/tornaia/karma-sonarqube-unit-reporter/blob/master/CHANGELOG.md) for the full list of changes. Please reopen if you still hit it with 1.0.0.
