### ISSUE TITLE
When was this forked?

### ISSUE THREAD

**Issue by tubbynl** [tornaia/karma-sonarqube-unit-reporter#8]
Do you have an indication of which version of the original karma-junit-reporter this was forked?

**Comment by tornaia** [comment]
I "forked" it on the 26th of January, 2016.
https://github.com/karma-runner/karma-junit-reporter/tree/3f43c511810f08e8b8c4ac2accead80740257261

**Comment by tubbynl** [comment]
tnx, this issue is closed then. 

i've tried replacing the original karma-junit-reporter plugin with yours and it run's but the results are not accepted by Sonar. I still need to research why when i've got the time and that might be a new ticket/pull request :)

**Comment by tornaia** [comment]
Im happy to help you so just paste here the logs... :-)

**Comment by tubbynl** [comment]
sorry for the delay :)

in order to use this plugin i've changed the following in our karma.conf.js:

`//reporters: ['progress', 'coverage', 'junit'],`
`reporters: ['progress', 'coverage', 'sonarqubeUnit'],`

`//junitReporter: {`
`sonarQubeUnitReporter: {`
`      useBrowserName: false, `
`      outputFile: 'target/surefire-reports/TEST-karma-junit-results.xml',`
`    },  `

And then it does output an junit result file (in XML but that's not allowed for uploading)
[TEST-karma-junit-results.txt](https://github.com/tornaia/karma-sonarqube-unit-reporter/files/263107/TEST-karma-junit-results.txt)

But that result file is not interpreted by SonarQube; the location of this file is identical and is compliant to the default path/file pattern SonarQube scans for for the junit results (i think; this previously worked)

**Comment by tubbynl** [comment]
en these are 2 logs of the running with the standard junit reported and this reporter, we run it via maven using https://github.com/eirslett/frontend-maven-plugin 

[log-karma-junit-reporter.txt](https://github.com/tornaia/karma-sonarqube-unit-reporter/files/263128/log-karma-junit-reporter.txt)
[log-karma-sonarqube-unit-reporter.txt](https://github.com/tornaia/karma-sonarqube-unit-reporter/files/263129/log-karma-sonarqube-unit-reporter.txt)

**Comment by tornaia** [comment]
Please give me some days to respond your findings - unfortunately (? :) I'm under heavy load...

**Comment by tubbynl** [comment]
np, thanks for the effort

**Comment by rodikal** [comment]
@tubbynl @tornaia I also had some problems getting the report accepted by Sonarqube
1. incorrect file names -> see #2 
2. duplicate test names -> now fixed by #12 (i previously fixed this locally by using a custom `testnameFormatter`)
