### ISSUE TITLE
Duration of a unit test must be at least 1

### ISSUE THREAD

**Issue by d-claassen** [tornaia/karma-sonarqube-unit-reporter#9]
The xsd describes the attribute `duration` as a `positiveInteger`:
```xsd
<xs:attribute name="duration" type="xs:positiveInteger" use="required"/>
```

This means it must be bigger than 0. It'd be nice if this plugin would catch such situations, and prevent any issues. This also means it should not set the default duration to 0, if no time is provided by the test result.

```javascript
var testCase = appendToThisNode.ele('testCase', {name: testnameFormatted, duration : (result.time || 0)});
```

I currently have a workaround in place that does this exact thing.
```javascript
    sonarQubeUnitReporter: {
      outputFile: 'ut_report.xml',
      useBrowserName: false,
      testnameFormatter: function(testname, result) {
        // Time must be at least 1 or analysis fails
        if(result.time === 0) {
          result.time = 1;
        }

        return testname;
      }
    }
```

**Comment by tornaia** [comment]
Great finding, many-many thanks!

I applied the fix and release a new (0.0.6) version! Please let me know if something is still not OK otherwise I will close this issue soon.
